[package]
name = "Brownhollow"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Douglas <github@darkdell.net>"]

[lib]
name = "brownhollow"
path = "src/lib.rs"

[[bin]]
name = "brownhollow"
path = "src/main.rs"

[dependencies]
